#!/bin/bash

# Author: Franco Massacesi (aka Chessi99)

#Colours
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

# Extract nmap information
function extractPort(){
	ports="$(cat allPorts | grep -oP '\d{1,5}/open' | awk '{print $1}' FS='/' | xargs | tr " " "," )"
	ip_address="$(cat allPorts | grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | sort -u | head -n 1)"
	echo -e "\n${blueColour}[*]${endColour} Extracting information...\n" > extractPorts.tmp
	echo -e "\t${blueColour}[*]${blueColour} IP Address: $ip_address"  >> extractPorts.tmp
	echo -e "\t${blueColour}[*]${endColour} Open ports: $ports\n"  >> extractPorts.tmp
	echo $ports
	cat extractPorts.tmp; rm extractPorts.tmp
}

echo -e "\n${yellowColour}[*]${endColour}${grayColour} Ejecutando el primer nmap${endColour}";
nmap -sC -sV -sS -p- --open -T5 -vvv -n -Pn $1 -oG allPorts
echo -e "\n${yellowColour}[*]${endColour}${grayColour} Extrayendo puertos${endColour}";
extractPort
echo -e "\n${yellowColour}[*]${endColour}${grayColour} Ejecutando el segundo escaneo con nmap para los puertos mas especificos${endColour}";
nmap -sC -sV -p$ports $1

for i in  $(echo $ports | tr "," "\n");
do
	echo $i;
done
